name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./SolucionSeguridad/Autorizacion.Middleware

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./SolucionSeguridad/Autorizacion.Middleware

      - name: Pack
        run: dotnet pack --configuration Release --output ./nupkgs
        working-directory: ./SolucionSeguridad/Autorizacion.Middleware

      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v3
        with:
          name: nupkgs
          path: ./nupkgs/*.nupkg

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download NuGet Packages
        uses: actions/download-artifact@v3
        with:
          name: nupkgs

      - name: List Files
        run: ls -R ./nupkgs

      - name: Add NuGet Source
        run: dotnet nuget add source --username Chris98310 --password ${{ secrets.Paquetes_Token }} --store-password-in-clear-text --name paquetes "https://nuget.pkg.github.com/Chris98310/index.json"

      - name: Push NuGet Packages to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.Paquetes_Token }} --source "paquetes" --skip-duplicate
