name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./SolucionSeguridad/Autorizacion.Middleware
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./SolucionSeguridad/Autorizacion.Middleware
    - name: Pack
      run: dotnet pack --configuration Release --output ./nupkgs
      working-directory: ./SolucionSeguridad/Autorizacion.Middleware
      
    - uses: actions/upload-artifact@v3
      with:
        name: Autorizacion.Middleware
        if-no-files-found: error
        retention-days: 7
        path: ./nupkgs/*.nupkg

  release:
    runs-on: ubuntu-latest    
    needs: build
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Download Artifacts 
      uses: actions/download-artifact@v3
      with:
        name: Autorizacion.Middleware
    
    - name: List Files
      run: ls -R ./nupkgs
      
    - name: Prep packages
      run: dotnet nuget add source --username Chris98310 --password ${{ secrets.PAQUETES_TOKEN }} --store-password-in-clear-text --name paquetes "https://nuget.pkg.github.com/Chris98310/index.json"
    - name: Push package to GitHub packages 
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.PAQUETES_TOKEN }} --source "paquetes" --skip-duplicate
